swagger: '2.0'
info:
  version: '1.0'
  title: aasif330au
  x-lastModified: '2022-01-24T14:45:06.000Z'
  description: details of bike
paths:
  /bike:
    get:
      produces:
        - application/json
        - application/xml
      responses:
        '201':
          description: Success response
          schema:
            $ref: '#/definitions/bike'
        '400':
          description: not found
          schema:
            type: array
            items:
              type: string
      parameters:
        - name: bikename
          in: query
          description: name of the bike
          required: true
          type: string
          format: ''
        - name: name
          in: header
          description: name of the bike
          required: true
          type: string
          format: ''
      operationId: getBike
      tags: []
    post:
      produces:
        - application/json
      responses:
        '200':
          description: added successfully
          schema:
            $ref: '#/definitions/GiveNewSchemaNameHere'
          examples:
            application/json:
              bike: pulsar
      parameters:
        - name: name
          in: query
          description: ''
          required: true
          type: string
          format: ''
        - name: body
          in: body
          description: ''
          schema:
            $ref: '#/definitions/GiveNewSchemaNameHere'
      operationId: postBike
      consumes:
        - application/json
    put:
      produces:
        - application/json
      responses:
        '200':
          description: bike added
      parameters:
        - name: name
          in: query
          description: bike name
          required: false
          type: string
          format: ''
        - name: body
          in: body
          description: description of the bike
          schema:
            $ref: '#/definitions/GiveNewSchemaNameHere'
      operationId: putBike
      consumes:
        - application/json
    patch:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters:
        - name: bike
          in: query
          description: name of the bike
          required: true
          type: string
          format: ''
        - name: body
          in: body
          description: ''
          schema:
            $ref: '#/definitions/GiveNewSchemaNameHere'
      operationId: patchBike
      consumes:
        - application/json
definitions:
  bike:
    name: karizma
    cc: '223'
    weight: 150kg
  GiveNewSchemaNameHere:
    type: object
    properties:
      name:
        type: string
        default: r15
      cc:
        type: string
        default: '300'
      weught:
        type: string
        default: '150'
