swagger: '2.0'
info:
  version: '1'
  title: ausamplecreated
  x-lastModified: '13 April 2022 1:19:44 pm (India Standard Time)'
paths:
  /asd:
    get:
      produces:
        - application/json
        - application/xml
      responses:
        '200':
          description: Success response
        '400':
          description: invalid request
      parameters:
        - name: a
          in: query
          description: dssf
          required: false
          type: string
          format: ''
          default: a
        - name: qas
          in: header
          description: asad sdafevr rffd
          required: false
          type: string
          format: ''
          default: '10'
      operationId: getAsd
      summary: xcdgdfsfs
      description: gfhdffdfmngbmvc  fjghfgd
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: postAsd
