swagger: '2.0'
info:
  version: '1'
  title: createdsample
  x-lastModified: '25 April 2022 2:48:29 pm (India Standard Time)'
paths:
  /asd:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
        '300':
          description: info
      parameters: []
      operationId: getAsd
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: postAsd
