swagger: '2.0'
info:
  version: '1'
  title: created340
  x-lastModified: '25 May 2022 11:14:26 am (India Standard Time)'
  description: sample created api
paths:
  /asd:
    get:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: getAsd
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: postAsd
