swagger: '2.0'
info:
  version: '2'
  title: rolled
  x-lastModified: '12 November 2020 10:18:23 am (India Standard Time)'
  description: ApI description added
paths:
  /pet:
    post:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters:
        - name: '1'
          in: query
          description: ''
          required: false
          type: string
          format: ''
        - name: header
          in: header
          description: ''
          required: false
          type: string
          format: ''
        - name: form
          in: formData
          description: ''
          required: false
          type: string
          format: ''
      operationId: postPet
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: description added
      summary: summery added
    put:
      produces:
        - application/json
      responses:
        '200':
          description: Success response
      parameters: []
      operationId: putPet
